### ISSUE TITLE
Problem with comission

### ISSUE THREAD

**Issue by WPinzonDev** [Randolio/randol_billing#1]
I've enabled debugging and enabled the commission. I've noticed that when charging a customer with the commission option enabled, it deducts money from the customer, but it doesn't add up in the job's or worker's bank account, nor does a payment received notification arrive. These are the errors with debugging enabled:
QBCORE TESTED
```
[      script:qb-core] SCRIPT ERROR: @qb-core/server/player.lua:236: attempt to index a nil value (local 'moneytype')
[      script:qb-core] > ref (@qb-core/server/player.lua:236)
[      script:qb-core] > AddMoney (@randol_billing/bridge/server/qb.lua:28)
[      script:qb-core] > handler (@randol_billing/sv_charge.lua:89)
[script:randol_billin] SCRIPT ERROR: error object is not a string
```

**Comment by WPinzonDev** [comment]
The error is easily fixed. In the qb.lua file, line 28, in the AddMoney function, replace 'account' with 'moneyType' and you're good to go.

```
function AddMoney(Player, moneyType, amount)
    Player.Functions.AddMoney(moneyType, amount, 'commission')
end
```

**Comment by Randolio** [comment]
Thankyou for this. Something I overlooked.
